name: Destroy Terraform (SAFE)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DELETE to confirm full destroy"
        required: true

jobs:

  destroy-infra:
    if: github.event.inputs.confirm == 'DELETE'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: mohamedamine050/repo_infra
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Infra
        working-directory: infra
        run: terraform init -reconfigure

      - name: Destroy Infra
        working-directory: infra
        run: terraform destroy -auto-approve


  destroy-bootstrap:
    needs: destroy-infra
    if: github.event.inputs.confirm == 'DELETE'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: mohamedamine050/repo_infra
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Bootstrap
        working-directory: bootstrap
        run: terraform init -reconfigure

      - name: Destroy Bootstrap
        working-directory: bootstrap
        run: terraform destroy -auto-approve
